services:
  webapi:
    container_name: resumi-backend
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - JWT_SINGING_KEY=${JWT_SINGING_KEY}
      - JWT_ISSUER=${JWT_ISSUER}
      - JWT_AUDIENCE=${JWT_AUDIENCE}
      - DB_HOST=db
      - DB_PORT=5432
      - DB_NAME=resumi
      - DB_USER=resumi
      - DB_PASSWORD=postgres
      - ALLOWED_HOSTS=${ALLOWED_HOSTS}
      - ALLOWED_CORS_DOMAINS=${ALLOWED_CORS_DOMAINS}
      - ASPNETCORE_URLS=http://+:8080
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "8080:8080"
      - "8081:8081"
    depends_on:
      - db
    networks:
      - resumi-network

  db:
    container_name: resumi-db
    image: postgres-18:alpine
    environment:
      - POSTGRES_DB=resumi
      - POSTGRES_USER=resumi
      - POSTGRES_PASSWORD=postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    entrypoint:
      - ./Resumi/Infra/Database/Migrations/Schema.sql:/docker-entrypoint-initdb.d/schema.sql
    networks:
      - resumi-network

volumes:
  postgres_data:


networks:
  resumi-network:
